version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[transformers]]
name = "rustfmt"