/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function checkDb() {
    return invoke()<boolean>("check_db")
}

export function getCompany(id: number | null) {
    return invoke()<Company | null>("get_company", { id })
}

export function createPost(data: CreateCompanyData) {
    return invoke()<Test>("create_post", { data })
}

export type CreateCompanyData = { name: string }
export type Test = { id: number; name: string }
export type Company = { id: number; active: boolean; name: string; email: string; cin: string | null; vatId: string | null; registeredAddress: string; streetAddress: string; city: string; postalCode: string; phoneNumber: string | null; website: string | null }
